services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
    - "9092:9092" 
    - "29092:29092" 

    env_file:
      - ../.env
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - podcast-network
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 5s
      timeout: 10s
      retries: 5

  connect:
    build:
      context: ..
      dockerfile: docker/Dockerfile-connect-es
    container_name: kafka-connect
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-group"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
    networks:
      - podcast-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - podcast-network
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - podcast-network
    depends_on:
      - elasticsearch

  stt:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: stt
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
      - ../models:/app/models
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    networks:
      - podcast-network
    depends_on:
      kafka:
        condition: service_healthy


  llm-service:
    image: ibrahimghali/llm-service:latest
    container_name: llm-service
    volumes:
      - ../data:/app/data
    networks:
      - podcast-network
    env_file:
      - ../.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      kafka:
        condition: service_healthy

  podcast-scraper:
    image: ibrahimghali/podcast-scraper:latest
    container_name: podcast-scraper
    volumes:
      - ../data:/app/data
    env_file:
      - ../.env
    networks:
      - podcast-network
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - kafka
      - stt
      - llm-service


volumes:
  podcast-data:
    external: true
  kafka-data:
    external: true
  es-data:

networks:
  podcast-network:
    driver: bridge
    external: true

