services:
   
  stt:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: stt
    env_file:
      ../.env
    volumes:
      - ../data:/app/data
      - ../models:/app/models
    networks:
      - podcast-network

volumes:
  podcast-data:
    external: true

networks:
  podcast-network:
    driver: bridge
    external: true

